### ISSUE TITLE
Create arguments string in object nMapInfo

### ISSUE THREAD

**Issue by dbeltman** [xebia-research/vulnmanager#69]
`nmap -T4 -oX nmap.xml -vv 192.168.1.1/24`
might need to be parsed to 
`-T4 192.168.1.1/24 `

So take out parts that are not relevant to the GUI-side of results, things like `-vv`, `-v`, or `-oX nmap.xml` do not affect anything visible in the GUI.
This would further enhance the visibility of called arguments in GUI

**Comment by KingToadz** [comment]
Baked strings with all information
